### PR TITLE
change september talks to october talks

### PR DESCRIPTION
**Pull request by Jarvis1010**

### CODE REVIEW

**Comment by BenDMyers** [comment]
@Jarvis1010 Could you please also change the filename to reflect the new date?

**Comment by Jarvis1010** [comment]
Did I forget to do that?  yes one sec

**Comment by BenDMyers** [comment]
> @Jarvis1010 Could you please also change the filename to reflect the new date?

Whoops, by this, I specifically mean the datestring in the filename.

**Review by BenDMyers — APPROVED** [review]
LGTM!

**Pull request merged**
