### PR TITLE
Add Round Table #0 Event

### PR DESCRIPTION
**Pull request by michaelgee22**

### CODE REVIEW

**Review by chantastic — COMMENTED** [review]
I love this idea! thank you for fleshing it out so well.

My only concern is that it will be quickly on the heals of single-threaded event — if I'm doing the timezone conversion correctly. Thoughts on maybe another fay of the week at this time?

**Comment by michaelgee22** [comment]
@chantastic so I actually chose this day because single-threaded is off this week and was intended to be at the same time as our usual events (hopefully I got it right)

**Comment by chantastic** [comment]
> @chantastic so I actually chose this day because single-threaded is off this week and was intended to be at the same time as our usual events (hopefully I got it right)

oh shoot! i missed that. so sorry! merge it in! i'm excited

**Comment by BenDMyers** [comment]
> @chantastic so I actually chose this day because single-threaded is off this week and was intended to be at the same time as our usual events (hopefully I got it right)


Seems like 18:00 GMT is 11am PDT. I think you want 17:00 GMT for our usual time?

**Comment by BenDMyers** [comment]
@all-contributors please add @michaelgee22 for content and event organizing

**Review by BenDMyers — APPROVED** [review]

**Pull request merged**
